web/router.ex
defmodule MunchHours.Router do
  use MunchHours.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :authenticated do
    plug MunchHours.Plug.Authenticate
  end

  scope "/users", MunchHours do
    pipe_through [:browser, :authenticated]
    get "/edit", TruckController, :edit
    post "/edit", TruckController, :update
    resources "/changecredentials", RegistrationController, only: [:new, :create]
  end

  scope "/", MunchHours do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end



  # Other scopes may use custom stacks.
  # scope "/api", MunchHours do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule MunchHours.LayoutView do
  use MunchHours.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Ever wonder when your favorite Münch Food Park truck will be open? Now you don't have to! Check this page for regularly updated">
    <title>Münch- Hours of Operation</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.ntcconsulting.info">Need Help?</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>
      
      <ul>
        <li><%= link "preview hours", to: page_path(@conn, :index) %></li>
        <%= if logged_in?(@conn) do %>
          <li><%= link "edit hours of operation", to: truck_path(@conn, :edit) %></li>
          <li><%= link "change login info", to: registration_path(@conn, :new) %></li>
          <li><%= link "logout", to: session_path(@conn, :delete), method: :delete %></li>
        <% end %>
      </ul>

      <div>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      </div>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

      <hr/>

      <footer class="pull-right">
        <div class="jumbotron">
          <h2><%= gettext "%{name}", name: "Münch- Hours of Operation" %></h2>
          <p class="lead">Weekly updated hours of operation for your favorite Münch Food Park trucks.</p>
        </div>
        <p>Powered by <a href="https://www.ntcconsulting.info">NTC Consulting</a></p>
      </footer>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/bare.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Ever wonder when your favorite Münch Food Park truck will be open? Now you don't have to! Check this page for regularly updated">
    <title>Münch- Hours of Operation</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>
  <body style="height: 100vh; width: 100vw; overflow-x: hidden; overflow-y: hidden; background-color: #45b3a2; margin-top: 0px;">
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>